fcm:
  key:
    path: moabuza-firebase-adminsdk-h9ox1-5af37638bf (1).json # ?? ???
    scope: https://www.googleapis.com/auth/cloud-platform


spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

#  spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#spring.datasource.url: jdbc:h2:mem:testdb
#spring.datasource.driverClassName: org.h2.Driver
#spring.datasource.username: sa
#spring.datasource.password:
#spring.jpa.database-platform: org.hibernate.dialect.H2Dialect